### ISSUE TITLE
Metadata Providers

### ISSUE THREAD

**Issue by kellnerd** [kellnerd/harmony#5]
List of sources/websites for which a metadata provider has been implemented or requested.

Leave a comment which includes at least a link to an example release for a quick provider request, or create a separate issue which is named after the provider and labeled with https://github.com/kellnerd/harmony/labels/provider if you have more research to share.
Detailed requests for sources with an open API and good documentation are more likely to be implemented.
_Edit:_ Let's be honest, every request which contains more details than just the name or URL of the source is probably worth its own issue already.

If you plan to work on a provider, be it doing more research or actually implementing it, please create a separate issue which is named after the provider and ask for it being assigned to you.

## Open JSON API

- [x] #49
- [x] Deezer (GTIN, ISRC)
- [x] iTunes (per region; no GTIN)
- [ ] Discogs (GTIN) (#170)
- [ ] YouTube (GTIN) (#31)

## Restricted JSON API

- [x] Spotify (requires token; GTIN, ISRC) (#16)
- [x] Tidal (requires token, per region; GTIN, ISRC) (#11)
- [ ] Qobuz ([documentation](http://web.archive.org/web/20180611030533/https://github.com/Qobuz/api-documentation), requires app ID, [IP-based 404s](https://community.metabrainz.org/t/qobuz-importer-script/569614/9?u=kellnerd) for unavailable regions; GTIN, ISRC)
- [ ] Apple Music (requires paid token; GTIN, ISRC)
- [ ] Beatport (requires token; GTIN, ISRC)
- [ ] Soundcloud (requires authentication; GTIN, ISRC) (#35)
- [ ] #12 (only accessible in some regions)
- [ ] #14 (requires authentication)

Tokens and other secrets should not be included in this repository but loaded from environment variables.

## HTML Scraping

- [x] Bandcamp (embedded JSON; GTIN)
- [x] Beatport (embedded JSON; GTIN, ISRC) (#2)
- [ ] OTOTOY (#34)

## Uncategorized Requests

- [ ] Melon, Bugs! and/or Genie ([via Discord](https://discord.com/channels/937555302251905084/937555302251905087/1159536953914568795))

**Comment by tigerman325** [comment]
My free time has been scarce these past few months. I like it, but I'll likely hold off on using it often until Spotify is included. It's puzzling why Spotify now limits visibility to only see releases in one's own country, but thankfully, a-tisket remains reliable for those releases if you know the URL. With some luck, I'll have the opportunity to explore it further.

**Comment by wileyfoxyx** [comment]
Would be interesting to see some kind of Yandex Music implantation is such service.

Example of an album: https://music.yandex.ru/album/12353342
Open JSON API: https://api.music.yandex.net/albums/12353342/ (or https://api.music.yandex.net/albums/12353342/with-tracks for additional info on tracks from album, such as the distributor of release). You might need VPN to open those, but the here's a mirror for the "with-tracks" response: https://www.jsonkeeper.com/b/YKSE

The API **does not** support neither GTAN nor ISRC.

There's also an unofficial implantation of an API at https://github.com/MarshalX/yandex-music-api/releases

**Comment by UltimateRiff** [comment]
one big provider (or two, depending on how you count it) I see missing is YouTube/YouTube Music. I feel like it might be right to kinda treat them seperately (as a user, not a developer)

the main things I know to look out for on YouTube

- metadata in the description is not at all standardized, perhaps save for distributed content (i.e. from distributors like DistroKid)
- a single video can have different titles, descriptions, and possibly different audio tracks per region
- often an album will be released as a single video with chapter markers for each track
- video titles are not standardized, sometimes containing the artist name or [official video] or other nonsense, which maybe should or shouldn't be removed from MusicBrainz submissions

I can make a ticket or two for this pair if you'd like~

**Comment by wileyfoxyx** [comment]
@UltimateRiff, I'd either would and would not count YouTube and YouTube Music as separate, mostly because of the so-called Art Tracks (that look like ordinary track in any music service on YTM yet as an ordinary video with "Provided to YouTube by..." line in the description on YT)

**Comment by reubot** [comment]
7digital.com has API docs at https://docs.7digital.com .

**Comment by c0b41** [comment]
[YouTube.js](https://github.com/LuanRT/YouTube.js) support youtube music api, no token required and GTIN search works.

**Comment by kellnerd** [comment]
@wileyfoxyx Thank you for the detailed request, this is enough to warrant a separate ticket. Can you please make one? (I will then leave my comments over there.)

@UltimateRiff One YouTube ticket should be enough for the start, we can always create a new ticket if it turns out there will be multiple providers and only one of them is implemented initially.
And the library suggested by @c0b41 should also be linked from there. Although I am not sure whether we will just have our own simple implementation inspired by the library, since we need to make requests in a way which is compatible with Harmony's caching.

If I am being honest, even a request with just a link to a good API documentation is enough for a separate issue. Can you please make one @reubot? I will clarify that in the description of this issue.

**Comment by phw** [comment]
PR #11 adds initial support for Tidal

**Comment by quantenzitrone** [comment]
I was about to suggest Amazon as a metadata provider, but [they don't support GTINs for albums](https://community.amazondeveloper.com/t/ability-to-view-and-search-by-album-upc/5021).

So right now, Amazon could only work as a standalone provider like Bandcamp.
They have a [restricted JSON API that is in Beta](https://developer.amazon.com/docs/music/API_web_albums.html) that seems quite good, but for authentication, you need to [contact the Amazon Business Development representative to get access to the API beta](https://developer.amazon.com/docs/music/API_web_LWA.html).

**Comment by quantenzitrone** [comment]
im just looking up random music streaming platforms at this point...

KKBOX is a Music Streaming Platform from Taiwan that is only available in Hong Kong, Japan, Macau, Malaysia, Singapore and Taiwan.
They have a restricted JSON api, that, similar to spotify, requires registering an application, which is free (as in gratis) and fairly easy.
While all the registering has to be done from an IP Address in one of the above countries (I managed to do that through a VPN) the API itself has no geo restrictions.

They also have good documentation https://docs-en.kkbox.codes/docs, however, they don't seem to have GTINs in their metadata.

You can use my access token for testing until it expires: `_oMkgQA5yo5GiY5IUvKJ6Q==`.
The access tokens seem to be valid for one month.

**Comment by quantenzitrone** [comment]
QQ Music has an api that doesn't include GTINs and ISRCs.
[The Documentation](https://developer.y.qq.com/docs/openapi#/overview) is completely in Chinese and getting an access token requires creating an account and asking them for authentication. So probably not worth it.

**Comment by HibiscusKazeneko** [comment]
Traxsource doesn't appear to have an API, so HTML scraping is probably the best we can do to get data.
Example release: https://www.traxsource.com/title/2292000/level-up

**Comment by quantenzitrone** [comment]
https://www.junodownload.com has or at least had a restricted API.
The docs are on archive.org: https://web.archive.org/web/20150501040915/http://www.junodownload.com:80/api/docs/JunoAPI_SEARCH_v1.3.1.pdf
it uses xml, and I cannot find any references to GTIN UPC Barcode or ISRC in the document, so it's likely not worth it to invest time into implementing their API.

**Comment by tigerman325** [comment]
> It seems that Qobuz can now search via GTIN/barcode now: catalog/search?query=4099964127652
> 
> Of course the API is still restricted :-/

I guess I'm doing something wrong, because it doesn't work for me.

**Comment by RyanThaDude** [comment]
> > It seems that Qobuz can now search via GTIN/barcode now: catalog/search?query=4099964127652
> > Of course the API is still restricted :-/
> 
> I guess I'm doing something wrong, because it doesn't work for me.

What I'm finding so far is that it has to precisely match the barcode, and I'm pretty sure Qobuz uses EAN (13 digit length) for their barcodes. Searching via barcode also works in the web player, but NOT for downloads.

**Comment by quantenzitrone** [comment]
try 
```sh
curl \
  --header 'X-User-Auth-Token: <your token>' \
  --url "https://www.qobuz.com/api.json/0.2/catalog/search?query=4099964127652&app_id=579939560"
```
don't tell anyone, but there are tokens [here](https://rentry.org/firehawk52#qobuz-tokens)

**Comment by EduardPrigoana** [comment]
you can use something like [qobuz-dl](https://github.com/QobuzDL/Qobuz-DL/) to search qobuz

**Comment by cottinghamk** [comment]
Discogs would be an incredible one here--for a lot of the labels I see, they're consistently one of the best repositories of data. I see they're on the list, but I don't see that anybody has linked their API documentation: https://www.discogs.com/developers

**Comment by prestonf22** [comment]
> you can use something like [qobuz-dl](https://github.com/QobuzDL/Qobuz-DL/) to search qobuz

Site already got taken down by Qobuz themselves

**Comment by tigerman325** [comment]
Discogs is terrible source for digital releases.

**Comment by UnviableFriend** [comment]
I see @Serial-ATA dug up some info on Bugs!, Melon, and Genie and made issues for them. Thank you for that! There is another two Korean streaming sites, maybe they have better APIs? [FLO](https://vibe.naver.com/artist/3980296) & [Naver's VIBE](https://www.music-flo.com/detail/artist/404372458/album) They all usually have the exact same info, much more consistent than western streaming services, so if any end up working that at least gets the bulk of the work done and it's not so bad manually grabbing a few more links. Also all of them now have more than 1,000 relationships on MusicBrainz(I added a count to one of my automatic nightly reports [here](https://unviablefriend.github.io/reports/missing_kr.html))

**Comment by Serial-ATA** [comment]
@UnviableFriend I can look into those over the weekend. I know SAMBL supports Naver, maybe @Lioncat6 has input on the complexity of that?

**Comment by Lioncat6** [comment]
@Serial-ATA  @UnviableFriend Naver is actually pretty simple to implement, but it does not have any external identifiers (UPCs/ISRCs). https://github.com/Lioncat6/SAMBL-React/blob/main/lib/providers/naver.ts

I'm about to PR a Qobuz provider as well!

**Comment by Serial-ATA** [comment]
Yeah, the other Korean sites (Bugs!, Melon, Genie) also don't have any external IDs unfortunately

**Comment by Lioncat6** [comment]
@Serial-ATA https://github.com/kellnerd/harmony/pull/206

**Comment by Serial-ATA** [comment]
@UnviableFriend #207 #208

**Comment by thatrobotdev** [comment]
It would be really cool to have Audius support! For example, for importing https://audius.co/chillhopmusic/album/chillhop-solarpunk

**Comment by chaban-mb** [comment]
Might I suggest [Volumo](https://en.wikipedia.org/wiki/Volumo)?

Tried analyzing the API and site metadata with AI. It looks like a promising and useful provider
https://gist.github.com/chaban-mb/1d91fed79ff09a042e0e4031ddd73e31

(Still needs to be fully verified, only lightly tested the results)

**Comment by chaban-mb** [comment]
Audius has a documented API:
https://docs.audius.co/api

[Free plan](https://api.audius.co/plans):
> 10 Requests/Second
> 500,000 Requests/Month

**Comment by Serial-ATA** [comment]
Does anyone know if there's already a list of the top streaming/download sites in the DB? I made a quick script to generate the top 50, not sure if it's accurate:

```
 1. apple.com                      (1,541,409 recordings, 1,617,366 releases)
 2. spotify.com                    (1,033,777 recordings, 1,160,739 releases)
 3. bandcamp.com                   (243,928 recordings, 1,527,026 releases)
 4. deezer.com                     (801,939 recordings, 942,909 releases)
 5. tidal.com                      (775,229 recordings, 508,910 releases)
 6. qobuz.com                      (269,671 recordings, 278,630 releases)
 7. soundcloud.com                 (42,429 recordings, 109,931 releases)
 8. beatport.com                   (80,534 recordings, 153,100 releases)
 9. youtube.com                    (134,251 recordings, 114,757 releases)
10. music.youtube.com              (64,052 recordings, 83,736 releases)
11. amazon.com                     (41,065 recordings, 64,249 releases)
12. mora.jp                        (166 recordings, 85,611 releases)
13. ototoy.jp                      (1 recordings, 48,592 releases)
14. junodownload.com               (133 recordings, 26,569 releases)
15. audiomack.com                  (19,106 recordings, 11,507 releases)
16. archive.org                    (2,378 recordings, 29,625 releases)
17. play.google.com                (499 recordings, 20,597 releases)
18. 7digital.com                   (44 recordings, 22,719 releases)
19. music.bugs.co.kr               (480 recordings, 16,559 releases)
20. melon.com                      (1,208 recordings, 15,213 releases)
21. boomplay.com                   (7,019 recordings, 10,174 releases)
22. traxsource.com                 (1,481 recordings, 8,128 releases)
23. genie.co.kr                    (90 recordings, 10,395 releases)
24. jamendo.com                    (526 recordings, 9,092 releases)
25. amazon.co.jp                   (545 recordings, 8,595 releases)
26. cdbaby.com                     (1 recordings, 9,432 releases)
27. recochoku.jp                   (392 recordings, 7,931 releases)
28. music.yandex.com               (117 recordings, 5,854 releases)
29. us.napster.com                 (835 recordings, 4,831 releases)
30. s.awa.fm                       (3,638 recordings, 2,976 releases)
31. pandora.com                    (1,314 recordings, 3,378 releases)
32. play.anghami.com               (1,150 recordings, 3,161 releases)
33. hdtracks.com                   (0 recordings, 5,723 releases)
34. e-onkyo.com                    (5 recordings, 5,202 releases)
35. boomkat.com                    (0 recordings, 4,415 releases)
36. vibe.naver.com                 (394 recordings, 1,999 releases)
37. vk.com                         (79 recordings, 2,977 releases)
38. music.monstercat.com           (2 recordings, 3,493 releases)
39. mixcloud.com                   (77 recordings, 3,194 releases)
40. music.line.me                  (132 recordings, 2,453 releases)
41. music.yandex.ru                (397 recordings, 1,735 releases)
42. last.fm                        (721 recordings, 2,338 releases)
43. store.steampowered.com         (40 recordings, 2,929 releases)
44. emusic.com                     (16 recordings, 2,638 releases)
45. iheart.com                     (570 recordings, 1,286 releases)
46. music.amazon.co.uk             (155 recordings, 1,687 releases)
47. kkbox.com                      (307 recordings, 1,462 releases)
48. bbc.co.uk                      (1,496 recordings, 1,143 releases)
49. mediafire.com                  (201 recordings, 2,040 releases)
50. beatsource.com                 (32 recordings, 2,077 releases)
```

**Comment by wileyfoxyx** [comment]
> Tried analyzing the API and site metadata with AI. It looks like a promising and useful provider

@chaban-mb may I ask what AI model & prompt(s) you used? Want to do the same analysis with some services too.

**Comment by Serial-ATA** [comment]
@wileyfoxyx If you want I can also dig into those services, assuming they aren't region locked

**Comment by wileyfoxyx** [comment]
@Serial-ATA they are sadly region-locked, so that's why I'm asking for the prompt.

**Comment by chaban-mb** [comment]
> may I ask what AI model & prompt(s) you used?

I've used [Google Antigravity](https://antigravity.google/) with Gemini Pro and the [browser subagent](https://antigravity.google/docs/browser-subagent) and let it browse the site. 

If you can't access the sites that probably won't help you much

**Comment by Lioncat6** [comment]
If you want to go poking around, a VPN is a good way to start. Typically a lot of overseas services allow registration via Google, so a testing account is quite useful.

My first point for poking around is typically using search boxes with previews/recommendations. (They almost always have very easily readable api calls) The network tab of inspect element is your friend.

I don't recommend using agents for this tbh, especially considering its likely to just get you IP blocked.

**Comment by chaban-mb** [comment]
> I don't recommend using agents for this tbh, especially considering its likely to just get you IP blocked.

I didn't have any trouble with this approach so far. Antigravity is running a Chrome browser in separate profile with a special extension to exfiltrate the DOM, screenshots, interact with the site similar to a human.  It can be more efficient than browsing by hand and copy-pasting logs, etc.

**Comment by wileyfoxyx** [comment]
>VPN is a good way to start.

Now that's where things get tricky. I am actually using VPN to access Copilot in my VS Code because it's geo locked, and our local websites require you to _disable_ VPN if you want to use them. (Mostly the big websites do that, though even the website for my university in a small town with population of 170k wouldn't load with VPN too)

**Comment by chaban-mb** [comment]
This is starting to become off-topic. Maybe continue this elsewhere?

**Comment by selfisekai** [comment]
What do you think about handling physical releases too? IMO particularly interesting providers would be Muziker (physical stores in CZ and SK, very international online) and bol.com (marketplace, BE and NL only). Both consistently expose GTINs and some limited metadata.
- https://www.muziker.nl/linkin-park-meteora-reissue-limited-edition-red-gold-splatter-lp
- https://www.muziker.cz/bts-arirang-living-legend-version-cd
- https://www.muziker.sk/the-rions-everything-every-single-day-transparent-white-coloured-lp
- https://www.bol.com/nl/nl/p/everything-every-single-day/9300000236955714/

Also lots of providers don't seem to expose a GTIN, but will nicely match one to a product.
- https://www.empik.com/szukaj/produkt?q=0093624844051
- https://www.cultura.com/search/results?search_query=3596974978867
- https://www.amazon.nl/s?k=8712629973185

**Comment by kellnerd** [comment]
Sorry, I forgot to reply here...

> What do you think about handling physical releases too?

I'm in favor of supporting stores and databases with a focus on physical releases as well. The Discogs provider was a first step into that direction and I have some other candidates in mind as well.
Preferably they would have higher than average quality of metadata and an API or at least a stable website, scraping something which is consistently changing layout is a nightmare.
Since I don't use any of your specific examples, I won't implement them, but I'm open to contributions. Eventually I probably have to ask for some maintenance guarantees as well since I can't look after every broken provider, but so far there is luckily only one broken Harmony provider (namely Beatport, scraping no longer works).

**Comment by Serial-ATA** [comment]
> Eventually I probably have to ask for some maintenance guarantees as well since I can't look after every broken provider

BTW feel free to assign me to issues that come up with any of the providers I add
